### ISSUE TITLE
unsupervised training dataset

### ISSUE THREAD

**Issue by hongyuntw** [abrazinskas/FewSum#2]
Hi, thank you for your great work first, I love your works!

I have some questions about unsupervised training steps
The paper said that 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/39511654/162575244-85956957-c93f-4058-8be9-95b5bc3af4d7.png">

And  the final pre-processed dataset provided by you be like
Example : 
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/39511654/162575393-3792a226-09ca-4669-92e1-28f7905ce7d9.png">

And here is my questions
1. What is the "group" means, and how did you arrange the group? (In my opinion the group is not mean the category of the product!?)
2. And in the example (the picture above), how do I know which review is `ri` during unsupervised training stage?

Thank you very much!

**Comment by abrazinskas** [comment]
1) A group is defined as a subset of reviews for a product or service. Review groups were created by random sampling. In the file, groups are indicated by the indx after product id. For example, 011231231_1, means that the group indx is 1 and the product/business id is 011231231.
2)  Each review will `act' as a pseudo-summary. If there are N reviews, there will be N summaries that are predicted in their own turn. This part is implemented in the datapipeline. 

Hope it helps, let me know if you have any other questions.

**Comment by hongyuntw** [comment]
Thank you very much !
